### ISSUE TITLE
Review design implementation for responsive navigation

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#10]
## Task 
Design review for responsive navigation

## Context
- [ ] Mobile nav items: [Home] [Filing] [Profile (links to the user's profile)] [Log out]
- [ ]  Selected is black vertical line (at desktop this line is horizontal)
- [ ] Hover is green vertical line (at desktop this line is horizontal)
- [ ] Line above and below each link is Gray 40
- [ ] Use of hamburger to show navigation (pull from cf.gov implementation)
- [ ] Use of "x" to hide navigation (pull from cf.gov implementation)

**Here's a mock-up:** 

Updated on 6/27/2024 (I may need to update the mock-ups to the latest):
<img width="1650" alt="Screenshot 2024-06-27 at 4 19 47 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/7a3fc59e-d21e-42de-9cf3-3bfc7771b8b3">
Loosely based on the consumerfinance.gov mobile megamenu. Let's pull the code that we can. https://www.consumerfinance.gov

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
I have reviewed this in dev pub and the PR has been merged. This will be included in work that will be merged into beta next week.  

I did find some issues in my review but we decided to move those to a separate task since they are not strictly related to the mobile navigation. 

https://github.com/cfpb/sbl-frontend/issues/1033
