### ISSUE TITLE
Update story template in project repo

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#20]
### Task
We have now made changes to our work process. The purpose of this task will be to determine what we would like to include in the updated story template on the sbl-project board. 

We can use this blank issue in sbl-project as our prototype: 
https://github.com/cfpb/sbl-project/issues/291

<img width="1425" alt="Screenshot 2024-10-28 at 2 35 02 PM" src="https://github.com/user-attachments/assets/33e59519-6013-4f63-a50c-01eb8f9e7502">

### Checklist
- [ ] Decide on what should be included in the new template
- [ ] Implement the change in GitHub
- [ ] Manually update current open stories to incorporate this new approach

**Comment by dan-padgett** [comment]
To better understand the scope here, are we:
- Trying to update the entire project repo template, or
- Trying to update how UX work is captured in project repo tickets?

**Comment by dan-padgett** [comment]
Given that, I think there are a few things we might want to consider as checklist items for UX:

1. Define design problem: this is kind of similar to the "Write initial user story" item in [293](https://github.com/cfpb/sbl-project/issues/293) but might be more aimed at revising any initial user stories (or recommending that they don't fit an actual user need) and gathering any other information we need (from data, e.g.).
2. Design exploration: initial creation of mockups to solve the design problem
3. Review options with team and decide on solution approach: this would make review at the design/dev sync a gate for moving forward. Included here could be any revisions that need to happen.
4. Finalize design and update acceptance criteria to reflect desired UI behavior: I think this is a nice way to "handoff" design work since there's a good chance that we'll have discovered use cases or interaction requirements while working on a solution.

Within UX tickets, we could obviously get a bit more granular. For instance, making sure that we're accounting for any relevant research by looking at the UX research and design question tracker during step 2 and adding any new questions as a part of step 4.

What do you think of those 4 steps as a general framework to start with for the user story template?

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
Here's an image of the _current_ template we're using. 

[![Image](https://github.com/user-attachments/assets/bd298f51-447c-4f0e-a440-4e732b081f75)
](url)

The main sections are: 
- Epic (the parent epic for the specific story)
- User story 
- Acceptance criteria
- Technical tasks

In your post it sounds like you are getting at how we can further refine the UX part of the "Technical tasks" section. Currently under UX we have the following: 

### UX
- [ ] Write initial user story
  - Review against task analysis for accuracy and relevance (if applicable)
  - Map story issue to the task analysis (if applicable)
- [ ] Validate user story with the team
- [ ] Review for specificity and completeness
- [ ] UX tasks that link to the UX repo

## Pass at applying what we discussed today

It seems as though a lot of what we've been discussing related to the backlog refinement process will pull a lot of items out of the UX section. Perhaps we may want to add a separate section called Story refinement or something like that. There we could track the progress that we discussed in this morning's meeting --- refinement ready, refinement in progress, refinement complete.

### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- Link to the parent epic issue

### User story
- As a [user type], I want to [take some action], so that [reason for action].

### Acceptance criteria
- Given [some context or conditions], when [the action that is performed], then [the expected observable outcome or behavior].

### Story refinement steps
- [ ] Refinement ready
- [ ] Refinement in progress
- [ ] Refinement complete

### Technical tasks
Team members should create technical tasks and add links (below) prior to sprint planning.

#### UX
- [ ] Task (link)
- [ ] Task (link)

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

#### Data
- [ ] Task (link)
- [ ] Task (link)

**Comment by angelcardoz** [comment]
Here is where we landed after working on the user story lifecycle, definition of ready, and definition of done. We will update the template to mirror the sections below. 

### Epic

Epic issue includes overview, complete list of user stories, user testing task ideation, and final design mock-ups.

- Link to the parent epic issue

### User story
- As a [user type], I want to [take some action], so that [reason for action].

### Acceptance criteria
- Given [some context or conditions], when [the action that is performed], then [the expected observable outcome or behavior].

### Tasks
Team members should create task issues in their respective repos and add links to those tasks below.

#### UX
- [ ] Task (link)
- [ ] Task (link)

#### Data
- [ ] Task (link)
- [ ] Task (link)

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

#### Data
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz Confirmed that this has been implemented.
