### ISSUE TITLE
Refine the definition of ready 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#26]
### Task
The purpose of this task will be refine the definition of ready to better reflect our updated process. 

## Definition of ready (existing) 
In order for a user story to be considered "ready", and brought into a sprint, the team must agree that it meets the following criteria.

- All dependencies have been identified
- UX requirements are complete, with UX resources linked to the user story
- Acceptance criteria is complete
- The story can be accomplished in a single sprint

We are moving to a process where UX, Content, Data, Frontend, and Backend are are tracked as a part of the story issue. So we will need to refine the definition of ready. 

## Definition of ready (first pass) 
In order for a user story to be considered "ready", the team must agree that it meets the following criteria. Additionally, each user story must be brought into a previous sprint to undergo "UX discovery", ensuring preliminary design thinking and necessary analysis are integrated effectively before development begins.
 
### UX discovery
- The story has been reviewed by the UX team to determine if there are any design implications
- If applicable, sections of task analysis that are impacted by the story have been updated or created
- If applicable, preliminary mock-ups are drafted and reviewed with the product owner for alignment with the user story and overall product vision
- UX resources are linked to the user story

### Acceptance criteria defined
- Acceptance criteria are clearly defined and agreed upon by the product owner, UX team, and development team
- These criteria include both functional requirements and, if applicable, design specifications

### Dependencies identified
- All dependencies are identified and a plan to address them is in place
- The story can be accomplished in a single sprint (discuss what this refers to)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
Here's an update on the definition of ready based on our conversations. Please review. 

I'm not sure where to place this but I think it's a valuable blurb to place somewhere.

"Each user story will be brought into a previous sprint to undergo "story refinement," ensuring that preliminary design thinking and necessary analysis are integrated effectively before design and development implementation begin."


### Definition of ready
For the user story to be considered "ready" the team must agree that it meets the following criteria: 
- [ ] Story is well-defined and we have minimized the possibility for surprises
- [ ] Acceptance criteria are clearly defined and agreed upon by involved parties (i.e. product owner, business analysts, UX, development, and data teams)
- [ ] All dependencies are identified and a plan to address them is in place

**Comment by dan-padgett** [comment]
@natalia-fitzgerald I'm note sure what this sentence means in the blurb you have:

> Each user story will be brought into a previous sprint to undergo "story refinement,"

Specifically, what it means to bring a story into a previous sprint. Can you clarify?

**Comment by natalia-fitzgerald** [comment]
> [@natalia-fitzgerald](https://github.com/natalia-fitzgerald) I'm note sure what this sentence means in the blurb you have:
> 
> > Each user story will be brought into a previous sprint to undergo "story refinement,"
> 
> Specifically, what it means to bring a story into a previous sprint. Can you clarify?

@dan-padgett 
No worries, we decided not to add this.
