### ISSUE TITLE
Refine the definition of done

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#29]
# Task
The purpose of this task will be refine the definition of done to better reflect our updated process. 

## [Definition of done (existing)](https://github.com/cfpb/sbl-project?tab=readme-ov-file#definition-of-done)
In order for a user story to be consider "done" and the issue closed, it must meet the following criteria:

- All acceptance criteria have been met.
- All UX requirements have been met.
- There are no known defects.
- Unit test coverage > 85%.
- Is deployed to the development environment.
- Documentation has been updated (if needed).

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
Here's an update on the definition of done to serve as a jumping off point. I will want to gather ideas from the development team to further build out and refine this list but thought it would be good to have a starting point. 

### Definition of done
For a user story to be consider "done", and the issue closed, it must meet the following criteria:
- [ ] All acceptance criteria have been met
- [ ] All UX requirements have been met; including a design review of the development implementation
- [ ] If required, the team has performed a bug bash
- [ ] There are no known defects
- [ ] Unit test coverage > 85%
- [ ] Has been deployed to the development environment
- [ ] Documentation has been updated (if needed)
